[package]
edition = "2021"
name = "lapce-prettier"
version = "0.0.0"
resolver = "2"

[dependencies]
anyhow = "1.0"
serde_json = "1.0"
jsonrpc-lite = "0.6.0"
once_cell = "1.17.0"
serde = "1.0.152"
lapce-plugin = { path = "../lapce-plugin-rust" }
