name = "lapce-prettier"
version = "2023.1.0"
display-name = "Lapce Prettier"
author = "Hanif Ariffin (hbina)"
description = "Prettier plugin for Lapce"
icon = "icon.png"
repository = "https://github.com/hbina/lapce-prettier"
wasm = "lapce-prettier.wasm"

[activation]
language = ["javascript","typescript","javascriptreact","typescriptreact"]
workspace-contains = [
    "**/**.js",
    "**/**.ts",
    "**/**.jsx",
    "**/**.tsx",
]

[config.prettierPath]
default = ""
description = """
Where the Prettier binary is located
"""
